# Generated by Django 3.1.1 on 2020-10-17 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
